### ISSUE TITLE
Upgrade Serverless framework version

### ISSUE THREAD

**Issue by kshychko** [hamlet-io/lambda-cloudwatch-slack#20]
## Expected Behaviour

Serverlsess framework version has been updated to support Python version upgrade to 3.9
## Current Behaviour

The lambda release GitHub action is falling now - https://github.com/hamlet-io/lambda-cloudwatch-slack/runs/5762049724?check_suite_focus=true
because python3.9 is not supported as a value of the provider.runtime property.
## Possible Solution

Follow the guide on https://www.serverless.com/framework/docs/guides/upgrading-v3#upgrading-to-v3
## Context

Upgrade to Serverless Framework v3 to keep the utility build/package process up to date.

**Comment by roleyfoley** [comment]
While you are there could you remove the package_lock.json file from the repo and add a git ignore for it. Instead I think we should just have a limited band of versions supported for serverless itself. Not really fussed that the dependent packages change between installs as we only use it as a utility.
